Taraxa-project/taraxa-platform

services/community-site/src/pages/Bounties/bounties.scss
services/community-site/src/pages/Profile/ViewProfile.tsx

Also adds a bit of padding on the bounty submissions list so that there's a bit of spacing between the hashed content and the username / date.

Fix submissions date display in user profile

---

services/community-site/tsconfig.json
services/delegation/src/config/delegation.ts
services/delegation/src/modules/delegation/balance.controller.ts
services/delegation/src/modules/delegation/delegation-nonce.entity.ts
services/delegation/src/modules/delegation/delegation.controller.ts
services/delegation/src/modules/delegation/delegation.module.ts
services/delegation/src/modules/delegation/delegation.service.ts
services/delegation/src/modules/delegation/dto/balances.dto.ts
services/delegation/src/modules/delegation/dto/create-delegation-nonce.dto.ts
services/delegation/src/modules/node/node-commission.entity.ts
services/delegation/src/modules/node/node.controller.ts
services/delegation/src/modules/node/node.entity.ts
services/delegation/src/modules/node/node.service.ts
services/delegation/src/modules/profile/profile.service.ts

- adds nonce route
- adds balances route
- adds stats fields to nodes
- fixes comission update
- adds comission precalculated fields
- adds totalDelegation precalculated field
- adds get node route
- fixes updating with empty values for node and profile
- adds yield and remainingDelegation field

Delegation backend

---

packages/taraxa-ui/src/components/Icons/Trophy.tsx
packages/taraxa-ui/src/components/Icons/index.ts
services/community-site/src/pages/Delegation/Delegation.tsx
services/community-site/src/pages/Delegation/delegation.scss
services/community-site/tsconfig.json

This PR adds the Trophy icon to `@taraxa-ui` and renders it on top nodes in the delegation page.

Render Trophy icon on top nodes

---

services/community-site/src/pages/Staking/Staking.tsx

Issue #42: Change Staking page title, tooltip and link

---

services/community-site/src/pages/Delegation/NodeProfilePage.tsx

Fixes #81 
Now the delegators list and count will be reset if the request fails.

#81 Fix delegators list resetting 

---

services/community-site/src/pages/Delegation/NodeProfilePage.tsx

Fixes #80 
Removed bad curly brace.

#80 Fixes community-delegated progress bar

---

packages/taraxa-ui/src/components/ProfileBasicCard/ProfileBasicCard.tsx
packages/taraxa-ui/src/components/ProfileBasicCard/profilebasiccard-styles.tsx
services/community-site/src/pages/Profile/ViewProfile.tsx
services/community-site/src/pages/Profile/profile.scss
services/community-site/src/services/useApi.ts

Show locked rewards in My Profile

---

services/community-site/src/pages/RunNode/RunNode.tsx
services/community-site/src/pages/RunNode/runnode.scss

Updated profile on run a node page

---

packages/taraxa-ui/src/components/BaseCard/basecard-styles.tsx
packages/taraxa-ui/src/components/DataCard/DataCard.tsx
packages/taraxa-ui/src/components/DataCard/datacard-styles.tsx
services/community-site/src/pages/Delegation/Delegation.tsx
services/community-site/src/pages/Staking/Staking.tsx

Staking page new design

---

services/community-site/src/App.tsx
services/community-site/src/components/Sidebar/Sidebar.tsx
services/community-site/src/components/Wallet.tsx
services/community-site/src/pages/Delegation/Delegation.tsx
services/community-site/src/pages/Delegation/Modal/Undelegate.tsx
services/community-site/src/pages/Delegation/NodeProfilePage.tsx
services/community-site/src/pages/Profile/ViewProfile.tsx
services/community-site/src/pages/Redeem/Redeem.tsx
services/community-site/src/pages/Staking/Modal/StakingSuccess.tsx
services/community-site/src/pages/Staking/Staking.tsx
services/community-site/src/services/useCMetamask.tsx
services/community-site/src/services/useChain.tsx

Change account addresses to be checksum

---

services/community-site/src/pages/Staking/Staking.tsx

#126 Fix bad undelegated number in Staking page

---

services/community-site/src/pages/Delegation/delegation.scss

#48: Change margin in delegation table

---

services/community-site/src/pages/Profile/ViewProfile.tsx

#126 profile breaking fix

---

services/community-site/src/pages/Delegation/Modal/Delegate.tsx
services/community-site/src/pages/Delegation/delegation.scss

#50: Add jdenticon to delegate modal

---

services/community-site/src/pages/Bounties/BountyDetails.tsx
services/community-site/src/pages/Bounties/bounties.scss

#56 Fixed bounties page table

---

.eslintrc.js
services/explorer/src/App.tsx
services/explorer/src/pages/Nodes/Nodes.effects.tsx
services/explorer/src/pages/Nodes/Nodes.tsx

feat(explorer): Created node page

---

services/claim-backend/src/modules/claim/claim.service.ts

NOTE: When a user changes his address, the community rewards move from the old address to the new one.

delegation: fixes changed addres balances

---

services/claim-backend/charts/claim-backend/templates/configmap.yaml
services/claim-backend/charts/claim-backend/values.yaml
services/claim-backend/charts/prod.values.yaml
services/claim-backend/charts/qa.values.yaml

adds values to helm

---

.circleci/config.yml
.circleci/workflows.yml
services/delegation/charts/community-delegation/templates/secrets.yaml
services/delegation/charts/community-delegation/values.yaml
services/delegation/charts/qa.values.yaml

Commits:
- run workflow to build helm chart for delegation
- fix missing secrets in values
- change keys in secret

Chore: added workflow to release helm-chart for delegation

---

services/community-site/src/pages/Delegation/Delegation.tsx

implements KYC restriction on delegation actions

---

services/community-site/src/pages/RunNode/Modal/RegisterNode.tsx

The validation error doesn't state exactly what is the INVALID_ARGUMENT check so best I could do was to check for `0x`

implements validation on vrf and proof fields

---

services/community-site/src/interfaces/Validator.ts
services/community-site/src/pages/RunNode/RunValidator.tsx
services/community-site/src/pages/RunNode/Table/MainnetValidatorRow.tsx
services/community-site/src/pages/Staking/Delegation.tsx
services/community-site/src/pages/Staking/Table/ValidatorRow.tsx
services/community-site/src/services/useExplorerStats.tsx
services/community-site/src/utils/validators.ts

@rattrap in the RunNode page we have "Expected yield" in the table. DO we want to display the newly calculated yields or keep the MAX 20% there?

Implements yield calculation and display

---

services/community-site/src/pages/Staking/Modal/Delegate.tsx
services/community-site/src/pages/Staking/Table/ValidatorRow.tsx
services/community-site/src/services/useExplorerStats.tsx

Updated Delegation buttons

---

services/community-site/src/components/Sidebar/Sidebar.tsx
services/community-site/src/pages/Home/Home.tsx
services/explorer/src/api/explorer-api/fetchInternalTransactions.ts
services/explorer/src/pages/TransactionData/TransactionData.effects.tsx
services/explorer/src/pages/TransactionData/TransactionData.tsx
services/explorer/src/pages/TransactionData/TransactionDataTables.tsx
services/explorer/src/pages/TransactionData/TransactionDataTabs.tsx
services/explorer/src/utils/getTransactionType.ts

Added table tab for internal transactions

---

services/explorer/src/api/explorer-api/fetchRevertReason.ts
services/explorer/src/api/types.ts
services/explorer/src/hooks/useExplorerNetwork.tsx
services/explorer/src/pages/TransactionData/TransactionData.effects.tsx
services/explorer/src/pages/TransactionData/TransactionData.tsx
services/explorer/src/utils/networks.ts

Implements tx failure reason fetch

---

packages/taraxa-ui/src/components/ProgressBar/ProgressBar.tsx
services/explorer/src/api/explorer-api/fetchHolders.ts
services/explorer/src/components/Tables/BlocksTable.tsx
services/explorer/src/components/Tables/Table.tsx
services/explorer/src/components/Tables/TransactionsTable.tsx
services/explorer/src/pages/Holders/HolderRow.tsx
services/explorer/src/pages/Holders/Holders.tsx
services/explorer/src/pages/Nodes/Nodes.tsx

Limited total holders and added 4 decimals to percentage

---

packages/taraxa-ui/src/components/Table/Table.tsx
packages/taraxa-ui/src/components/Table/index.ts
packages/taraxa-ui/src/index.ts
services/community-site/src/pages/Staking/Delegation.tsx
services/community-site/src/pages/Staking/delegation.scss

Added sorting to validators

---

services/explorer/src/api/explorer-api/fetchRevertReason.ts

fixes eth_call parameters

---

services/community-site/src/pages/Redeem/Redeem.tsx
services/community-site/src/pages/RunNode/RunValidator.tsx
services/community-site/src/pages/Staking/Delegation.tsx
services/community-site/src/pages/Staking/NodeProfilePage.tsx

Fixed issue refresh on actions

---

services/community-site/src/pages/Staking/Delegation.tsx
services/community-site/src/services/useDelegation.tsx
services/community-site/src/services/useDpos.ts

Added claim all functionality

---

services/explorer/src/pages/Faucet/Faucet.tsx

(feat): Added helper text on faucet page
